CREATE TABLE `bibtex_import_task` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `teacher_id` BIGINT NOT NULL,
    `source_type` VARCHAR(32) NOT NULL,
    `file_name` VARCHAR(255) NULL,
    `status` VARCHAR(32) NOT NULL,
    `total_count` INT NOT NULL DEFAULT 0,
    `success_count` INT NOT NULL DEFAULT 0,
    `failed_count` INT NOT NULL DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_bibtex_import_task_teacher_created` (`teacher_id`, `created_at`),
    CONSTRAINT `fk_bibtex_import_task_teacher` FOREIGN KEY (`teacher_id`) REFERENCES `teacher_profile` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `bibtex_import_item` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `task_id` BIGINT NOT NULL,
    `teacher_id` BIGINT NOT NULL,
    `status` VARCHAR(32) NOT NULL,
    `error_message` VARCHAR(1000) NULL,
    `duplicate_status` VARCHAR(32) NOT NULL DEFAULT 'NONE',
    `duplicate_paper_id` BIGINT NULL,
    `raw_entry` TEXT NULL,
    `entry_type` VARCHAR(64) NULL,
    `bib_key` VARCHAR(255) NULL,
    `title` VARCHAR(500) NULL,
    `authors` TEXT NULL,
    `journal` VARCHAR(255) NULL,
    `booktitle` VARCHAR(255) NULL,
    `year` INT NULL,
    `doi` VARCHAR(255) NULL,
    `volume` VARCHAR(64) NULL,
    `number` VARCHAR(64) NULL,
    `pages` VARCHAR(64) NULL,
    `publisher` VARCHAR(255) NULL,
    `url` VARCHAR(1024) NULL,
    `abstract_text` TEXT NULL,
    `keywords` VARCHAR(1000) NULL,
    `selected` TINYINT(1) NOT NULL DEFAULT 1,
    `created_paper_id` BIGINT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_bibtex_import_item_task` (`task_id`, `id`),
    KEY `idx_bibtex_import_item_teacher_status` (`teacher_id`, `status`),
    KEY `idx_bibtex_import_item_teacher_doi` (`teacher_id`, `doi`),
    CONSTRAINT `fk_bibtex_import_item_task` FOREIGN KEY (`task_id`) REFERENCES `bibtex_import_task` (`id`),
    CONSTRAINT `fk_bibtex_import_item_teacher` FOREIGN KEY (`teacher_id`) REFERENCES `teacher_profile` (`id`),
    CONSTRAINT `fk_bibtex_import_item_duplicate_paper` FOREIGN KEY (`duplicate_paper_id`) REFERENCES `paper` (`id`),
    CONSTRAINT `fk_bibtex_import_item_created_paper` FOREIGN KEY (`created_paper_id`) REFERENCES `paper` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
