CREATE TABLE `ocr_task` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `teacher_id` BIGINT NOT NULL,
    `file_id` BIGINT NOT NULL,
    `target_type` VARCHAR(32) NOT NULL,
    `recognition_mode` VARCHAR(32) NULL,
    `status` VARCHAR(32) NOT NULL,
    `error_message` VARCHAR(1000) NULL,
    `raw_text` MEDIUMTEXT NULL,
    `result_count` INT NOT NULL DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_ocr_task_teacher_created` (`teacher_id`, `created_at`),
    KEY `idx_ocr_task_teacher_file` (`teacher_id`, `file_id`),
    CONSTRAINT `fk_ocr_task_teacher` FOREIGN KEY (`teacher_id`) REFERENCES `teacher_profile` (`id`),
    CONSTRAINT `fk_ocr_task_file` FOREIGN KEY (`file_id`) REFERENCES `file_metadata` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ocr_result` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `task_id` BIGINT NOT NULL,
    `teacher_id` BIGINT NOT NULL,
    `target_type` VARCHAR(32) NOT NULL,
    `status` VARCHAR(32) NOT NULL,
    `confidence` DECIMAL(6,4) NULL,
    `result_json` JSON NULL,
    `title` VARCHAR(500) NULL,
    `authors` TEXT NULL,
    `publication_name` VARCHAR(255) NULL,
    `publication_type` VARCHAR(64) NULL,
    `publish_year` INT NULL,
    `doi` VARCHAR(255) NULL,
    `volume` VARCHAR(64) NULL,
    `issue` VARCHAR(64) NULL,
    `pages` VARCHAR(64) NULL,
    `publisher` VARCHAR(255) NULL,
    `url` VARCHAR(1024) NULL,
    `abstract_text` TEXT NULL,
    `keywords` VARCHAR(1000) NULL,
    `patent_name` VARCHAR(255) NULL,
    `patent_number` VARCHAR(128) NULL,
    `patent_type` VARCHAR(128) NULL,
    `patent_status` VARCHAR(64) NULL,
    `application_date` DATE NULL,
    `authorization_date` DATE NULL,
    `inventors` TEXT NULL,
    `certificate_name` VARCHAR(255) NULL,
    `certificate_type` VARCHAR(128) NULL,
    `issuing_authority` VARCHAR(255) NULL,
    `issue_date` DATE NULL,
    `description` TEXT NULL,
    `created_record_id` BIGINT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_ocr_result_task` (`task_id`, `id`),
    KEY `idx_ocr_result_teacher_status` (`teacher_id`, `status`),
    CONSTRAINT `fk_ocr_result_task` FOREIGN KEY (`task_id`) REFERENCES `ocr_task` (`id`),
    CONSTRAINT `fk_ocr_result_teacher` FOREIGN KEY (`teacher_id`) REFERENCES `teacher_profile` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
